name: Backend Build and Tests

on:
  workflow_call:  # This makes it reusable
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '24'
      working-directory:
        description: 'Working directory for backend'
        required: false
        type: string
        default: './backend'
    # secrets:
    #   JWT_SECRET_KEY:
    #     required: true
    #   MONGO_URI:
    #     required: true
    #   NODE_ENV:
    #     required: true
    outputs:
      build-status:
        description: "Build status"
        value: ${{ jobs.backend.outputs.status }}

jobs:
   backend:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build.outcome }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}