name: Test & Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger Vercel
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"

